### ISSUE TITLE
Is it possible to upgrade .Net Standard 2.0?

### ISSUE THREAD

**Issue by aqa510415008** [TomPallister/Ocelot#120] opened 2017-08-28 02:23 UTC
@TomPallister @binarymash @geffzhang 友善大神 
Looking forward to Ocelot upgrade to .Net Standard 2.0?

**Comment by TomPallister** [comment] 2017-08-29 18:54
Hi @aqa510415008 thanks for contributing! This is a duplicate of #114 

I am going to start working on the upgrade asap. Unfortunately it is not going to be simple.

**Closed by TomPallister** 2017-08-29 18:54 UTC
