### ISSUE TITLE
how to configure to support different api？

### ISSUE THREAD

**Issue by hanyubao** [TomPallister/Ocelot#91] opened 2017-04-27 06:53 UTC
I am new to Ocelot and have created a demo gateway project successfully.
The question is how to support many different api(s).
For example:
**webapi A**  on  http://a.com
/api/product
/api/user
... other 10 resources.
  
**webapi B** on http://b.com
/api/order
/api/address
....other 20 resources.
not only  get or put。
so is there any good way to configure ？

or we can configure  as this:

"ReRoutes": [
    {
      "DownstreamPathTemplate": "/api/{controller}}",
      "DownstreamScheme": "http",
      "DownstreamHost": "a.com",
      "DownstreamPort": 80,
      "UpstreamPathTemplate": "/api/**webapi1**/{controller}",
      "UpstreamHttpMethod": "**Get,Post,Put,Delete**"
    },
     {
      "DownstreamPathTemplate": "/api/{controller}}",
      "DownstreamScheme": "http",
      "DownstreamHost": "a.com",
      "DownstreamPort": 80,
      "UpstreamPathTemplate": "/api/webapi2/{controller}",
      "UpstreamHttpMethod": "Get,Post,Put,Delete"
    }
  ]

Any reply is appreciated.

**Comment by juancash** [comment] 2017-04-27 07:09
Hi @hanyubao,
with the current version you must map all resources, but recently was made a modification to manage many api(s) more easyly (#89). I guess this changes will be available soon in Nuget package but @TomPallister can say you with more exactly. While you can use the code of the master branch if you are in a hurry.

**Comment by hanyubao** [comment] 2017-04-27 07:19
thank you @juancash

**Comment by TomPallister** [comment] 2017-04-27 07:45
@juancash I can release a new version now I think..give me a few minutes! Just enough time before work starts! :)

**Comment by TomPallister** [comment] 2017-04-27 08:00
@juancash Ive just released 1.4.3, your change will be in it! :D

**Comment by juancash** [comment] 2017-04-27 08:06
@TomPallister Excellent, thank you very much :D

@hanyubao you can use the new version to implement your scenario.

**Comment by hanyubao** [comment] 2017-04-27 08:30
@TomPallister @juancash 
That's great! Thanks for all your effort.

**Comment by juancash** [comment] 2017-04-27 15:12
@TomPallister 
Hi again, I´m using the version 1.4.3 but seems something works different or something is wrong, because now my "POST" requests are not working. Seems something about the headers, but I´m not sure. I´m trying to debug to found where is the problem. If I use the version 1.4.2 or the branch that I pushed in #89 all works fine. Do you know if has changed the way of process the request types, headers or body in the requests? 
Thanks.

**Comment by juancash** [comment] 2017-04-27 16:37
@TomPallister It seems that at least the content-type comes empty to the api (after pass by the gateway).

**Comment by TomPallister** [comment] 2017-04-28 08:20
@juancash I will look at it asap! might be something to do with recent refactoring!

**Comment by TomPallister** [comment] 2017-04-28 12:04
Ive found the issue and am fixing atm!

**Comment by TomPallister** [comment] 2017-04-28 12:21
@juancash @hanyubao I have pushed version 1.4.4, this should fix the issue with no content type when using POST. It was a regression brought in after some refactoring. 

I have only written a failing unit test and made it pass, I have not had time to manually test yet but I'm confident this is the problem and it will work now -_-

**Comment by binarymash** [comment] 2017-04-28 12:27
Sorry, looks like it was my refactoring in #88 that broke this!

**Comment by TomPallister** [comment] 2017-04-28 12:30
Easy to miss and there should have already been a unit test around it so my fault! Its nice to work on a code base where you can just add a failing test though :)

**Comment by juancash** [comment] 2017-04-28 13:45
@binarymash @TomPallister 
No problem ;) . Thanks to both of you for your effort and speed.

**Comment by TomPallister** [comment] 2017-05-09 21:00
Going to close this issue now i think @juancash changes have solved the problem. It is much easier to configure re route ;)

Massive thanks for the work @juancash !!

**Closed by TomPallister** 2017-05-09 21:00 UTC

**Comment by hanyubao** [comment] 2017-05-16 06:55
@juancash   thx for your help,but is there a nuget release or version for this issue? any  final document for multipe verbs is welcome.
@TomPallister have a good holiday^_^

**Comment by juancash** [comment] 2017-05-16 17:26
@hanyubao yes, you can download the project and use the code in master until a new version is published in the nuget. Remember that now the UpstreamHttpMehtod property is a list.

You can see an example in the PR # 94.
